name: fluento
description: A beginner-friendly language learning application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Declare your image assets here so Flutter can bundle them in the app
  assets:
    - assets/images/logo.png
    - assets/images/reading.jpg
    - assets/images/writing.jpg
    - assets/images/speaking.jpg
    - assets/images/listening.jpg
